[project]
name = "mcp-property-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.1",
    "fastapi-mcp>=0.4.0",
    "fastmcp>=2.13.0.2",
    "uvicorn>=0.38.0",
]
